version: "3.8"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - 8086:8086
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    env_file:
      - .env
    environment:
     - GF_INSTALL_PLUGINS=pr0ps-trackmap-panel
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/track:/usr/share/grafana/public/maps
    ports:
      - 3000:3000
    depends_on:
      - influxdb
  app:
    container_name: app
    image: dataacquisition_app:latest
    restart: always
    build:
      context: ./app
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app
        target: /app
    working_dir: /app
    ports:
      - 169.254.48.219:65432:65432 # This is the IP address that the telemetry system connects to
    depends_on:
      - influxdb
  # use with docker-compose --profile sim up --build
  sim:
    container_name: sim
    image: dataacquisition_sim:latest
    restart: always
    build:
      context: ./sim
    ports:
      - 65433:65433
    volumes:
      - type: bind
        source: ./sim
        target: /sim
    working_dir: /sim
    depends_on:
      - app
    profiles:
      - sim
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    command: grafana influxdb
volumes: 
  influxdb:
  grafana_storage:
